### ISSUE TITLE
Lambda deployment

### ISSUE THREAD

**Issue by FRosner** [codecentric/serverless-astra-graalvm#8]
- S3 push
- deploy new version
- https://github.com/vertx-howtos/aws-native-image-lambda-howto
- https://www.kabisa.nl/tech/beat-java-cold-starts-in-aws-lambdas-with-graalvm/
- https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest?

**Comment by FRosner** [comment]
```
{
    "events": [
        {
            "timestamp": 1622135450982,
            "message": "java.lang.ClassNotFoundException: com.github.codecentric.LambdaHandler\n",
            "ingestionTime": 1622135451189
        },
        {
            "timestamp": 1622135450982,
            "message": "at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)\n",
            "ingestionTime": 1622135451189
        },
        {
            "timestamp": 1622135450982,
            "message": "at java.lang.Class.forName(DynamicHub.java:1295)\n",
            "ingestionTime": 1622135451189
        },
        {
            "timestamp": 1622135450982,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.invoke(LambdaRuntime.java:156)\n",
            "ingestionTime": 1622135451189
        },
        {
            "timestamp": 1622135450982,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.main(LambdaRuntime.java:386)\n",
            "ingestionTime": 1622135451189
        },
        {
            "timestamp": 1622135451052,
            "message": "START RequestId: d711dcd1-b043-4879-9d8b-6523e6aec40a Version: $LATEST\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451128,
            "message": "java.lang.ClassNotFoundException: com.github.codecentric.LambdaHandler\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451128,
            "message": "at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451128,
            "message": "at java.lang.Class.forName(DynamicHub.java:1295)\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451128,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.invoke(LambdaRuntime.java:156)\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451128,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.main(LambdaRuntime.java:386)\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451168,
            "message": "END RequestId: d711dcd1-b043-4879-9d8b-6523e6aec40a\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451168,
            "message": "REPORT RequestId: d711dcd1-b043-4879-9d8b-6523e6aec40a\tDuration: 115.59 ms\tBilled Duration: 116 ms\tMemory Size: 128 MB\tMax Memory Used: 9 MB\t\n",
            "ingestionTime": 1622135451221
        },
        {
            "timestamp": 1622135451168,
            "message": "Unknown application error occurred\n\n",
            "ingestionTime": 1622135451221
        }
    ],
    "nextForwardToken": "f/36174829374001082102320265310482883836442405236060061704",
    "nextBackwardToken": "b/36174829369853143495393569406118629065720691288666603520"
}
```

**Comment by FRosner** [comment]
We might need some more stuff in the `reflect.json`: https://github.com/VR4J/aws-enriching-lambda-authorizer/blob/feature/graal-vm/reflect.json

**Comment by FRosner** [comment]
```
{
    "events": [
        {
            "timestamp": 1622138973640,
            "message": "START RequestId: 16d5dc8b-5fcf-41e2-b57a-9bc77f644081 Version: $LATEST\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973701,
            "message": "java.lang.ClassNotFoundException: java.lang.Object\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973701,
            "message": "at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973702,
            "message": "at java.lang.Class.forName(DynamicHub.java:1295)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973702,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.getParameterType(LambdaRuntime.java:336)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973702,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.invokeMethod(LambdaRuntime.java:287)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973703,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.invokeLambdaRequestHandler(LambdaRuntime.java:251)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973703,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.invokeClass(LambdaRuntime.java:208)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973703,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.invoke(LambdaRuntime.java:164)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973703,
            "message": "at com.formkiq.lambda.runtime.graalvm.LambdaRuntime.main(LambdaRuntime.java:386)\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973722,
            "message": "END RequestId: 16d5dc8b-5fcf-41e2-b57a-9bc77f644081\n",
            "ingestionTime": 1622138977320
        },
        {
            "timestamp": 1622138973722,
            "message": "REPORT RequestId: 16d5dc8b-5fcf-41e2-b57a-9bc77f644081\tDuration: 81.23 ms\tBilled Duration: 210 ms\tMemory Size: 128 MB\tMax Memory Used: 50 MB\tInit Duration: 128.67 ms\t\n",
            "ingestionTime": 1622138977320
        }
    ],
    "nextForwardToken": "f/36174907929580284167160939282485451588903529719990386699",
    "nextBackwardToken": "b/36174907927751623060881428184879522690546364076499992576"
}
```

**Comment by FRosner** [comment]
All errors fixed now :) We have a simple lambda handler that takes any json object and returns an empty json object :)
